categories:
  une:
    label: "À la une"
    sources:
      lemonde:
        name: "Le Monde"
        rss: "https://www.lemonde.fr/rss/une.xml"

      lefigaro:
        name: "Le Figaro"
        rss: "https://www.lefigaro.fr/rss/figaro_actualites.xml"

      liberation:
        name: "Libération"
        rss: "https://www.liberation.fr/arc/outboundfeeds/rss-all/collection/accueil-une/?outputType=xml"

      lequipe:
        name: "L'Équipe"
        rss: "https://dwh.lequipe.fr/api/edito/rss?path=/"

      franceinfo:
        name: "France Info"
        rss: "https://www.franceinfo.fr/titres.rss"

      mondediplomatique:
        name: "Le Monde Diplomatique"
        rss: "https://www.monde-diplomatique.fr/rss/"

